### PR TITLE
Fixes

### LINKED ISSUE #473: [CRF General Bug] Spectator Role Icon needs to be scaled for smaller overall icon

### PR DESCRIPTION
**Pull request by Salamiboio**
- Adds alive player list
- Adds first person spectate feature
- Adds listening modes UI indicator
- Adds VON Channels
- Adds Private VON Channels with requests
- Revamped the entire UI

### CODE REVIEW

**Comment by tanaaKa** [comment]
Upon testing in dedi server tool:

image

**Comment by tanaaKa** [comment]
Small bug:
image

Replicated by doing:
Going into spec
Hold U
Choose a slot
Click game

**Comment by Salamiboio** [comment]
Do it in server tools, groups in the regular workbench perform weirdly, i get this error when they don't exist at all in the workbench but disappears in the actual game.

**Comment by tanaaKa** [comment]
Everything I've posted is in server tools

**Comment by tanaaKa** [comment]
image

There are entities being spawned when you turn on listening mode. Turning off listening mode leaves the entity where you toggled it off.

**Comment by Salamiboio** [comment]
Weird, listening mode doesn't create a new entity, just changes your EOnFrame location from 0 10000 0 to your cameras location. It has to be with how icons are drawn and undrawn, will look into it.

**Comment by tanaaKa** [comment]
> Weird, listening mode doesn't create a new entity, just changes your EOnFrame location from 0 10000 0 to your cameras location. It has to be with how icons are drawn and undrawn, will look into it.

I fixed it. Review the commit above. 

EOnInit -> EOnPostInit

Edit: this fixes m_bIsListening too

**Comment by Salamiboio** [comment]
Solid, appreciate it

**Comment by Njpatman** [comment]
> image
> 
> There are entities being spawned when you turn on listening mode. Turning off listening mode leaves the entity where you toggled it off.

@Salamiboio also, could you reduce the stroke of the red outline in the compass by one or two pixels and maybe try a darker red?

**Comment by Salamiboio** [comment]
It's 2 pixels wide rn, 1 doesn't give it a proper outline.

**Comment by Salamiboio** [comment]
> > Weird, listening mode doesn't create a new entity, just changes your EOnFrame location from 0 10000 0 to your cameras location. It has to be with how icons are drawn and undrawn, will look into it.
> 
> I fixed it. Review the commit above.
> 
> EOnInit -> EOnPostInit
> 
> Edit: this fixes m_bIsListening too

This breaks everything as EOnInit is needed to set the event masks

override void EOnInit(IEntity owner)
	{
		SetEventMask(owner, EntityEvent.FIXEDFRAME);
		SetEventMask(owner, EntityEvent.INIT);
	}

This will cause huge lag on the server

**Comment by tanaaKa** [comment]
> > > Weird, listening mode doesn't create a new entity, just changes your EOnFrame location from 0 10000 0 to your cameras location. It has to be with how icons are drawn and undrawn, will look into it.
> > 
> > 
> > I fixed it. Review the commit above.
> > EOnInit -> EOnPostInit
> > Edit: this fixes m_bIsListening too
> 
> This breaks everything as EOnInit is needed to set the event masks
> 
> override void EOnInit(IEntity owner) { SetEventMask(owner, EntityEvent.FIXEDFRAME); SetEventMask(owner, EntityEvent.INIT); }
> 
> This will cause huge lag on the server

It was already broken. You were causing a memory leak that was crashing the client after ~120s of running in a dedicated environment. We'll need another fix that doesn't create a race condition with entity init order.

**Comment by Salamiboio** [comment]
It's crashing cause of the lack of connection to the backend

**Comment by Salamiboio** [comment]
I am getting it too even in this new branch

**Comment by Salamiboio** [comment]
Someone with a better computer please test this but it seems setting the InitialEntity's VON range to 0m makes it so they can't talk locally making constant listening possible

**Comment by tanaaKa** [comment]
You done with this @Salamiboio?

**Comment by tanaaKa** [comment]
Nvm, I hear nothing in testing spec.

**Comment by tanaaKa** [comment]
Any idea?
image

**Comment by tanaaKa** [comment]
Also yes, verified no audio. Will tag you with video in discord.

**Comment by Salamiboio** [comment]
> Any idea?
> image
> 

Same issue with trying to access the modded SCR_ChimeraCharacter before it's initialized

**Review by tanaaKa — DISMISSED** [review]

File: scripts/Game/Systems/UI/Spectator/CRF_SpectatorMenu.c [hunk 1]
```diff
@@ -180,18 +706,40 @@ class CRF_SpectatorMenuUI: ChimeraMenuBase
...
+			if (item.FindComponent(BaseRadioComponent))
 				radioEntity = item;
 		}
 		BaseRadioComponent radio = BaseRadioComponent.Cast(radioEntity.FindComponent(BaseRadioComponent));
 		radio.SetPower(true);
 		RadioTransceiver transiver = RadioTransceiver.Cast(radio.GetTransceiver(0));
-		transiver.SetFrequency(1);
+		float multiplier = m_Gamemode.GetChannel(SCR_PlayerController.GetLocalPlayerId());
+		RadioHandlerComponent rhc = RadioHandlerComponent.Cast(GetGame().GetPlayerController().FindComponent(RadioHandlerComponent));
+		Print(multiplier);
```
Comment (Njpatman) [inline scripts/Game/Systems/UI/Spectator/CRF_SpectatorMenu.c]: comment out print pls

**Review by Njpatman — APPROVED** [review]
