### PR TITLE
Another gearscript data rewirte

### LINKED ISSUE #644: [CRF General Bug] GUID blank on gearscripts
00:06:52.042    RESOURCES (E): Wrong GUID/name for resource @"{0000000000000000}Prefabs/Characters/Factions/CIV/CRF_GS_CIV_MO_P.et" in property "<missing-def>"

### PR DESCRIPTION
**Pull request by Njpatman**
Implements a new Role Config for all roles and fixes the GUID error for gear resets

Fixes: #644

### CODE REVIEW

**Review by tanaaKa — APPROVED** [review]

File: scripts/Game/Systems/Core/Managers/CRF_RplToAuthorityManager.c [hunk 1]
```diff
@@ -396,7 +396,7 @@ class CRF_RplToAuthorityManager : ScriptComponent
 			prefab
 		);
 		
-		//m_SlottingManager.UpdateSlotResource(m_SlottingManager.GetPlayerSlotID(playerId), prefab);
+		m_SlottingManager.UpdateSlotResource(m_SlottingManager.GetPlayerSlotID(playerId), prefab);
```
Comment (tanaaKa) [inline scripts/Game/Systems/Core/Managers/CRF_RplToAuthorityManager.c:399]: Just verifying this is on purpose

Comment (Njpatman) [reply scripts/Game/Systems/Core/Managers/CRF_RplToAuthorityManager.c:399]: yep, that's how we update a player's slot when their gearscript gets reset (primarily for respawns)
