### PR TITLE
Bug Fix | Fixes shareable markers

### LINKED ISSUE #1106: [CRF General Bug] Shareable markers are still bugged for JIPs

### PR DESCRIPTION
**Pull request by Salamiboio**
Fixes https://github.com/CoalitionArma/Coalition-Reforger-Framework/issues/1106

### CODE REVIEW

File: scripts/Game/Systems/Core/Managers/CRF_RplToAuthorityManager.c [hunk 1]
```diff
@@ -1959,6 +1963,16 @@ class CRF_RplToAuthorityManager : ScriptComponent
...
 		if (!factionManager)
 			return;
+		
+		SCR_MapMarkerManagerComponent mapMarkerManager = SCR_MapMarkerManagerComponent.GetInstance();
+		if (!mapMarkerManager)
+			return;
+		
+		Faction localPlayerFaction = factionManager.GetPlayerFaction(playerId);
+		
+		if (!mapMarkerManager.m_aGlobalMarkers.Contains(markerUID) && localPlayerFaction)
```
Comment (tanaaKa) [inline scripts/Game/Systems/Core/Managers/CRF_RplToAuthorityManager.c]: Race condition possibility here by inserting here and can cause markers to be added multiple time if the players share the same marker. Maybe do it before calling the RPC in `ShareMapMarkerGlobal`?

File: scripts/Game/Systems/Core/Managers/CRF_RplToAuthorityManager.c [hunk 2]
```diff
@@ -2043,4 +2057,48 @@ class CRF_RplToAuthorityManager : ScriptComponent
...
 		}
 	}
+	
+	void RequestGlobalMarkerRefresh()
+	{
+		Rpc(RpcAsk_RequestGlobalMarkerRefresh, SCR_PlayerController.GetLocalPlayerId());
+	}
+	
+	[RplRpc(RplChannel.Reliable, RplRcver.Server)]
+	void RpcAsk_RequestGlobalMarkerRefresh(int playerId)
```
Comment (tanaaKa) [inline scripts/Game/Systems/Core/Managers/CRF_RplToAuthorityManager.c:2063]: Missing telemetry and should be in the rpc managers

File: scripts/Game/Systems/VanillaOverrides/CRF_SCR_PlayerController.c [hunk 3]
```diff
@@ -199,4 +204,19 @@ modded class SCR_PlayerController
...
 			mapMarkersMan.UpdateAllMarkerVisibilities();
     }
+	
+	void RefreshGlobalMarkers(array<int> markers)
+	{
+		Rpc(RpcDo_RefreshGlobalMarkers, markers);
+	}
+	
+	[RplRpc(RplChannel.Reliable, RplRcver.Owner)]
+	void RpcDo_RefreshGlobalMarkers(array<int> markers)
```
Comment (tanaaKa) [inline scripts/Game/Systems/VanillaOverrides/CRF_SCR_PlayerController.c:221]: Missing telemetry and should be in the rpc managers

File: scripts/Game/Systems/Core/Managers/CRF_RplToAuthorityManager.c [hunk 4]
```diff
@@ -1947,6 +1947,10 @@ class CRF_RplToAuthorityManager : ScriptComponent
 		if (!playerFaction)
 			return;
 		
+		SCR_MapMarkerManagerComponent mapMarkerManager = SCR_MapMarkerManagerComponent.GetInstance();
```
Comment (tanaaKa) [inline scripts/Game/Systems/Core/Managers/CRF_RplToAuthorityManager.c]: Redundant mapMarkerManager assignment

File: scripts/Game/Systems/Core/Managers/CRF_RplToAuthorityManager.c [hunk 5]
```diff
@@ -1959,6 +1963,16 @@ class CRF_RplToAuthorityManager : ScriptComponent
 		SCR_FactionManager factionManager = SCR_FactionManager.Cast(GetGame().GetFactionManager());
 		if (!factionManager)
 			return;
+		
+		SCR_MapMarkerManagerComponent mapMarkerManager = SCR_MapMarkerManagerComponent.GetInstance();
```
Comment (tanaaKa) [inline scripts/Game/Systems/Core/Managers/CRF_RplToAuthorityManager.c]: Redundant mapMarkerManager assignment

File: scripts/Game/Systems/VanillaOverrides/CRF_SCR_PlayerController.c [hunk 6]
```diff
@@ -15,6 +15,11 @@ modded class SCR_PlayerController
 		
 		if (!Replication.IsServer())
```
Comment (tanaaKa) [inline scripts/Game/Systems/VanillaOverrides/CRF_SCR_PlayerController.c:23]: What happens if a player joins, leaves, and then rejoins? There's also no cleanup for `m_aGlobalMarkers` if they get deleted.

File: scripts/Game/Systems/VanillaOverrides/Managers/CRF_SCR_MapMarkerManagerComponent.c [hunk 7]
```diff
@@ -19,6 +20,31 @@ modded class SCR_MapMarkerManagerComponent
...
+	
+	//Method used for JIPs to get markers placed during safestart
+	void RefreshGlobalMarkers(array<int> globalMarkers)
+	{
+		SCR_MapMarkerManagerComponent mapMarkerManager = SCR_MapMarkerManagerComponent.GetInstance();
+		if (!mapMarkerManager)
+			return;
+		
+		//Nested loop to ensure all global markers are enabled that should be.
+		foreach (int markerUID: globalMarkers)
```
Comment (tanaaKa) [inline scripts/Game/Systems/VanillaOverrides/Managers/CRF_SCR_MapMarkerManagerComponent.c]: Hell fucking nah. This is terrible code. Let me explain:

With a double for/foreach, you're applying a O(n²) complexity to a look up. So, for example, if you were to have 100 global markers and 100 static markers (IE a CCO), that would result in 10000 comparisons between the two loops.

If we apply a marker map instead, we simplify it to O(1) complexity:
```c#
void RefreshGlobalMarkers(array<int> globalMarkers)
{
    SCR_MapMarkerManagerComponent mapMarkerManager = SCR_MapMarkerManagerComponent.GetInstance();
    if (!mapMarkerManager)
        return;

    // Build a map of markerID -> marker for O(1) lookups
    map<int, SCR_MapMarkerBase> markerMap = new map<int, SCR_MapMarkerBase>;
    foreach (SCR_MapMarkerBase marker: mapMarkerManager.GetStaticMarkers())
    {
        markerMap.Set(marker.GetMarkerID(), marker);
    }

    // Now just do direct lookups instead of nested iteration
    foreach (int markerUID: globalMarkers)
    {
        SCR_MapMarkerBase marker = markerMap.Get(markerUID);
        if (marker && !marker.m_bIsShared)
            marker.m_bIsShared = true;
    }

    UpdateAllMarkerVisibilities();
}
```
code not checked fwiw, check in enfusion in case I messed up

**Review by tanaaKa — CHANGES_REQUESTED** [review]

File: scripts/Game/Systems/Core/Managers/CRF_RplToAuthorityManager.c (hunk 1 above)
Comment (Salamiboio) [reply scripts/Game/Systems/Core/Managers/CRF_RplToAuthorityManager.c]: ShareMapMarkerGlobal is only called when a map marker is placed in safestart. This isn't tied to the action for sharing the map marker

File: scripts/Game/Systems/VanillaOverrides/CRF_SCR_PlayerController.c (hunk 3 above)
Comment (Salamiboio) [reply scripts/Game/Systems/VanillaOverrides/CRF_SCR_PlayerController.c:221]: Can't broadcasts to the owner of the playercontroller.

File: scripts/Game/Systems/Core/Managers/CRF_RplToAuthorityManager.c (hunk 2 above)
Comment (Salamiboio) [reply scripts/Game/Systems/Core/Managers/CRF_RplToAuthorityManager.c:2063]: Added telemetry, already in the RPC Manager

File: scripts/Game/Systems/Core/Managers/CRF_RplToAuthorityManager.c (hunk 4 above)
Comment (Salamiboio) [reply scripts/Game/Systems/Core/Managers/CRF_RplToAuthorityManager.c]: Added singleton for it

File: scripts/Game/Systems/VanillaOverrides/CRF_SCR_PlayerController.c (hunk 3 above)
Comment (Salamiboio) [reply scripts/Game/Systems/VanillaOverrides/CRF_SCR_PlayerController.c:221]: Added telemetry, remains in playercontroller as it broadcasts to the owner of it

File: scripts/Game/Systems/Core/Managers/CRF_RplToAuthorityManager.c (hunk 5 above)
Comment (Salamiboio) [reply scripts/Game/Systems/Core/Managers/CRF_RplToAuthorityManager.c]: Added singleton

File: scripts/Game/Systems/VanillaOverrides/Managers/CRF_SCR_MapMarkerManagerComponent.c (hunk 7 above)
Comment (Salamiboio) [reply scripts/Game/Systems/VanillaOverrides/Managers/CRF_SCR_MapMarkerManagerComponent.c]: Added and works

File: scripts/Game/Systems/VanillaOverrides/CRF_SCR_PlayerController.c (hunk 6 above)
Comment (Salamiboio) [reply scripts/Game/Systems/VanillaOverrides/CRF_SCR_PlayerController.c:23]: Now removes markers when they are deleted
